### ISSUE TITLE
Installer hangs if authenticity of github.com not previously known.

### ISSUE THREAD

**Issue by brian-pond** [superchargejs/installer#2]
**Steps to duplicate:**

1. New machine.
2. Clone the repository for superchargejs/installer.
3. Execute command:  `node cli.js new mytest` or  `supercharge new mytest`

The following error will **briefly** flash on the terminal, and then **disappear**.  I had to debug to catch it.  But it was there.

> The authenticity of host 'github.com (192.30.253.112)' can't be established.
> RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
> Are you sure you want to continue connecting (yes/no)?

This will hang the installer indefinitely.  User must CTRL + C to break.

This is an edge case; most users will have previously encountered and accepted the prompt.

Suggestion to fix:  Before executing ListR (which calls Execa), run some validation checks.  Catch the above scenario cleanly, and avoid hanging because of the dialog box.

**Comment by marcuspoehls** [comment]
@PMojito Good catch Brian!

The installer uses the repo’s git-URL for cloning. We can fix this by using the repository’s HTTPS-URL.

Do you want to send a PR for this change?
